# ~/.config/helix/config.toml

# theme = "everforest_dark"
theme = "gruvbox"

[editor]
line-number = "relative"
mouse = true
cursorline = true
middle-click-paste = true
scrolloff = 6
auto-format = true
auto-pairs = true
auto-completion = true
path-completion = true
end-of-line-diagnostics = "hint"
true-color = true
bufferline = "multiple"
rulers = [80,100]
color-modes = true
undercurl = true
# undofile = true
# auto-info = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
# display-inlay-hints = true
display-progress-messages = true

[editor.whitespace]
render = "all"

[editor.auto-save]
focus-lost = true

[editor.indent-guides]
render = true
# rainbow-option = "dim"

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
center = ["position", "position-percentage", "total-line-numbers"]
right = ["diagnostics", "workspace-diagnostics", "selections", "register", "file-encoding", "file-type", "version-control"]

[keys.normal.space]
i = ":toggle lsp.display-inlay-hints" # toggle inlay hints
