# [[language]]
# name = "rust"
# auto-format = true

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
check = "clippy"
cargo.features = "all"
inlayHints.bindingModeHints.enable = true
inlayHints.typeHints.hideClosureInitialization = true
