"set termguicolors
if !has('gui_running')
  set t_Co=256
endif

" https://github.com/morhetz/gruvbox
"let g:gruvbox_termcolors=256
let g:gruvbox_italic=1
let g:gruvbox_transparent_bg=1
let g:gruvbox_contrast_dark='hard'
set background=dark
colorscheme gruvbox

" https://github.com/itchyny/lightline.vim
set laststatus=2
set ttimeout ttimeoutlen=50
"set showmode
set noshowmode

syntax on
set nu
set relativenumber
set mouse=a
set clipboard=unnamedplus,unnamed
set ruler
set showcmd
"set listchars=tab:→\ ,eol:↲,nbsp:•,trail:␣,extends:⟩,precedes:⟨,space:•
"set showbreak=↪\
"set list

set tabstop=4
set softtabstop=4
set shiftwidth=4
set shiftround
set expandtab
set smarttab
set autoindent
set smartindent

set hlsearch
set incsearch
set ignorecase
set smartcase
set showmatch
"set cpoptions+=x

set splitbelow
set splitright

set autoread
set wrapscan
"set noswapfile

"set wrap breakindent
"set linebreak

"set lazyredraw
"set cursorline
"set colorcolumn=81
"set signcolumn=yes
"set laststatus=2
"set scrolloff=3

"set hidden
"set nobackup
"set nowritebackup

"set updatetime=300
"set ttimeoutlen=50

"filetype plugin on

