"set termguicolors
if !has('gui_running')
  set t_Co=256
endif

" https://github.com/morhetz/gruvbox
let g:gruvbox_termcolors=256
let g:gruvbox_italic=1
let g:gruvbox_transparent_bg=1
let g:gruvbox_contrast_dark='hard'
set background=dark
colorscheme gruvbox

" https://github.com/itchyny/lightline.vim
set laststatus=2
set ttimeout ttimeoutlen=50
"set showmode
set noshowmode

syntax on
filetype plugin indent on
filetype plugin on

" https://github.com/rust-lang/rust.vim?tab=readme-ov-file
" run :RustFmt when save
let g:rustfmt_autosave = 1

set nu
set relativenumber
set mouse=a
set clipboard=unnamedplus,unnamed
set ruler
set showcmd
"set listchars=tab:→\ ,eol:↲,nbsp:•,trail:␣,extends:⟩,precedes:⟨,space:•
"set showbreak=↪\
"set list

set tabstop=4
set softtabstop=4
set shiftwidth=4
set shiftround
set expandtab
set smarttab
set autoindent
set smartindent

set hlsearch
set incsearch
set ignorecase
set smartcase
set showmatch
"set cpoptions+=x

set splitbelow
set splitright

set autoread
set wrapscan
"set noswapfile

"set wrap breakindent
"set linebreak

"set lazyredraw
"set cursorline
"set colorcolumn=81
"set signcolumn=yes
"set laststatus=2
"set scrolloff=3

"set hidden
"set nobackup
"set nowritebackup

"set updatetime=300
"set ttimeoutlen=50


" ## added by OPAM user-setup for vim / base ## d611dd144a5764d46fdea4c0c2e0ba07 ## you can edit, but keep this line
let s:opam_share_dir = system("opam var share")
let s:opam_share_dir = substitute(s:opam_share_dir, '[\r\n]*$', '', '')

let s:opam_configuration = {}

function! OpamConfOcpIndent()
  execute "set rtp^=" . s:opam_share_dir . "/ocp-indent/vim"
endfunction
let s:opam_configuration['ocp-indent'] = function('OpamConfOcpIndent')

function! OpamConfOcpIndex()
  execute "set rtp+=" . s:opam_share_dir . "/ocp-index/vim"
endfunction
let s:opam_configuration['ocp-index'] = function('OpamConfOcpIndex')

function! OpamConfMerlin()
  let l:dir = s:opam_share_dir . "/merlin/vim"
  execute "set rtp+=" . l:dir
endfunction
let s:opam_configuration['merlin'] = function('OpamConfMerlin')

let s:opam_packages = ["ocp-indent", "ocp-index", "merlin"]
let s:opam_available_tools = []
for tool in s:opam_packages
  " Respect package order (merlin should be after ocp-index)
  if isdirectory(s:opam_share_dir . "/" . tool)
    call add(s:opam_available_tools, tool)
    call s:opam_configuration[tool]()
  endif
endfor
" ## end of OPAM user-setup addition for vim / base ## keep this line
" ## added by OPAM user-setup for vim / ocp-indent ## 9e79b106acc1dbf52e42e870cca1542f ## you can edit, but keep this line
if count(s:opam_available_tools,"ocp-indent") == 0
  source "/Users/zhy/.opam/default/share/ocp-indent/vim/indent/ocaml.vim"
endif
" ## end of OPAM user-setup addition for vim / ocp-indent ## keep this line
